output_root: runs
leaderboard_csv: ${hydra:runtime.cwd}/reports/benchmark_results.csv
learning_rate: 3e-5
head_learning_rate: null 
gradient_accumulation_steps: 1
metric_average: macro
warmup_steps: 50 #following dnabert2 paper
epochs: 3 # default values overwritten by task, all values that appear both here and in tasks are default 
train_bs: 16 # bs = batch_size
eval_bs: 16
weight_decay: 0.01
eval_strategy: steps
save_strategy: steps
save_total_limit: 1
logging_steps: 20
eval_steps: 250
save_steps: 250
eval_accumulation_steps: ${oc.select:data.tasks.${data.task}.eval_accumulation,null}
metric_for_best_model: f1
early_stopping_patience: 5
early_stopping_threshold: 0.0
fp16: true
report_to: mlflow 
enable_mlflow: true
mlflow_tracking_uri: file:${hydra:runtime.cwd}/mlruns
mlflow_experiment: ${experiment_name}