name: zhihan1996/DNA_bert_3
trust_remote_code: false
max_length: 512
sequence_preprocess: kmer
kmer: 3
import_modules: []
label_mode: class_index
problem_type: single_label_classification
set_label_mapping: true