type: transformer
name: InstaDeepAI/nucleotide-transformer-v2-500m-multi-species
trust_remote_code: true
revision: 06615c1660c892fc199840c18123f8385b3542a8
max_length: 2048 #if breaks try decreasing
import_modules: []
label_mode: class_index
use_lora: true
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: "query,value,key,dense"
frozen_backbone: false